baseURL = "https://irisyao.me"
title = "年年"

theme = "hugo-theme-puppet"
themesDir = "./themes/"

copyright = ""
paginate = 3
languageCode = "zh"
defaultContentLanguage = "zh"

hasCJKLanguage = true
enableInlineShortcodes = true
enableEmoji = true

googleAnalytics = ""

[outputs]
home = ["HTML", "JSON", "RSS"]

[taxonomies]
category = "categories"
tag = "tags"

[markup]
# https://gohugo.io/functions/transform/highlight/
[markup.highlight]
noClasses = true
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = false
style = "dracula"

[markup.goldmark.renderer]
unsafe = true

[params]
author = "IrisYao"
description = "有一些问题不会有答案 有一些事情总会有遗憾 也许未来会使我更完整"
keywords = "blog,developer,frontend,backend,engineer,shanghai"
img_home = "img/home-bg.jpg"
img_404 = "img/404-bg.jpg"

[params.brand]
avatar = "img/avatar.jpg"

# [params.sidebar]
[params.sidebar]
gravatarEmail = ""
# Overwritten by your gravatar image if `gravatarEmail` is filled
avatar = "img/home-bg.jpg"
bio = "Iris"

[menu]
[[menu.main]]
identifier = "blog"
name = "博客"
url = "/"
weight = -100
# [[menu.main]]
# identifier = "archive"
# name = "Archive"
# url = "/archive/"
# weight = 10
# [[menu.main]]
# identifier = "guide"
# name = "Guide"
# url = "/series/themes-guide/"
# weight = 20
# [[menu.main]]
# identifier = "about"
# name = "About"
# url = "/about/"
# weight = 50
# [[menu.main]]
# identifier = "friends"
# name = "Friends"
# url = ""
# weight = 100


useFaviconGenerator = true

custom_js = []
custom_css = [] # ["css/custom.css"]  Add your file to assets folder  [assets/css/custom.css]

[params.social]
# twitter = "johndoe"
# facebook = "johndoe"
# zhihu = "johndoe"
# weibo = "johndoe"
# github = "iris"
# gitlab = "johndoe"
# linkedin = "johndoe"
# rss = true
# [params.social.mastodon]
# weight = 56
# icon = "fab fa-mastodon"
# format = "https://mastodon.social/%v"
# id = "mock"
# url = ""

# [[params.friends]]
# name = "Windmgc"
# url = "https://gohugo.io"

# [[params.friends]]
# name = "Windmgc"
# url = "https://gohugo.io"

# See https://giscus.app/
# [params.giscus]
# enable = true
# repo = "roninro/hugo-theme-puppet"
# repo_id = "R_kgDOHuvyhw"
# category = "General"
# category_id = "DIC_kwDOHuvyh84CQjDo"
# input_position = "top"
# theme = "light_tritanopia"
# lang = "en"